from typing import Protocol

from contexts.catalog.domain import ProductRecord, ProductStatus, ProductSummary


class CatalogRepository(Protocol):
    def initialize(self) -> None: ...
    def seed_products(self, products: list[ProductRecord]) -> None: ...
    def list_products(self) -> list[ProductRecord]: ...
    def list_summaries(self) -> list[ProductSummary]: ...
    def get_by_id(self, product_id: str) -> ProductRecord | None: ...
    def get_by_slug(self, slug: str) -> ProductRecord | None: ...
    def create_product(self, product: ProductRecord) -> ProductRecord: ...
    def update_product(self, product: ProductRecord) -> ProductRecord: ...
    def update_status(self, product_id: str, status: ProductStatus) -> ProductRecord | None: ...
