from typing import Protocol

from contexts.fulfillment.domain import (
    FulfillmentEvent,
    FulfillmentNote,
    FulfillmentTaskRecord,
)


class FulfillmentRepository(Protocol):
    def initialize(self) -> None: ...
    def seed_tasks(self, tasks: list[FulfillmentTaskRecord]) -> None: ...
    def seed_events(self, events: list[FulfillmentEvent]) -> None: ...
    def seed_notes(self, notes: list[FulfillmentNote]) -> None: ...
    def list_tasks(self) -> list[FulfillmentTaskRecord]: ...
    def list_events(self) -> list[FulfillmentEvent]: ...
    def list_notes(self) -> list[FulfillmentNote]: ...
    def update_task_status(
        self, task_id: str, status: str
    ) -> FulfillmentTaskRecord | None: ...
