from typing import Protocol

from contexts.inventory.domain import InventoryLevelRecord


class InventoryRepository(Protocol):
    def initialize(self) -> None: ...
    def seed_levels(self, levels: list[InventoryLevelRecord]) -> None: ...
    def list_levels(self) -> list[InventoryLevelRecord]: ...
    def get_level(self, sku: str, location_id: str) -> InventoryLevelRecord | None: ...
    def upsert_level(self, level: InventoryLevelRecord) -> InventoryLevelRecord: ...
