from typing import Protocol

from contexts.auth.domain import AuthAccountRecord


class AuthAccountRepository(Protocol):
    def initialize(self) -> None: ...
    def seed_accounts(self, accounts: list[AuthAccountRecord]) -> None: ...
    def get_by_email(self, email: str) -> AuthAccountRecord | None: ...
    def get_by_id(self, user_id: str) -> AuthAccountRecord | None: ...
