from typing import Protocol

from contexts.user.domain import UserRecord, UserSummary


class UserRepository(Protocol):
    def initialize(self) -> None: ...
    def seed_users(self, users: list[UserRecord]) -> None: ...
    def get_by_id(self, user_id: str) -> UserRecord | None: ...
    def list_summaries(self) -> list[UserSummary]: ...
    def update_status(self, user_id: str, status: str) -> UserRecord | None: ...
